### ISSUE TITLE
cities_light.models.City.objects.all() as default query slows app with all countries

### ISSUE THREAD

**Issue by darahsten** [yourlabs/django-cities-light#173]
Hi,

I had a situation in development where I found my template rendering for in excesses of 800 seconds from an average of 1second. Turned out this was arising from City.objects.all() when all countries are loaded.

This is how the documented example is made and was what I followed.

I think it would be good to inform people that such a query might slow down template rendering or better default to a query that loads only a manageable set of cities in the documentation

**Comment by mpasternak** [comment]
I agree. This is important. Please provide patch for the documentation, submit a pull request and reopen.

**Comment by jpic** [comment]
Was this due to a Select field ?

**Comment by darahsten** [comment]
Yes, this was to a select field.

**Comment by jpic** [comment]
@darahsten this is a classical kind of issue with django because forms do not include any javascript out of the box, and therefore generated forms can't be used as-is (ie. file upload is another exemple).
Perhaps try to use an app for autocompletion then you can have minimal database hit when rendering a selection field ?
