### ISSUE TITLE
Missing Migration

### ISSUE THREAD

**Issue by qiu-lijie** [yourlabs/django-cities-light#263]
Noticed a missing migration file from the project when upgrading to 3.9.0, however seems like it may have existed for a while now. 

root@4ecd6a56c6c2:/mysite# python manage.py makemigrations
Migrations for 'cities_light':
  /usr/local/lib/python3.8/site-packages/cities_light/migrations/0011_auto_20220219_1945.py
    - Alter field id on city
    - Alter field id on country
    - Alter field id on region
    - Alter field id on subregion

Steps to reproduce
```
pip install django django-cities-light
django-admin startproject mysite
cd mysite
# add 'cities_light' to mysite/settings.py with your favourite editor
# nano mysite/settings.py
python manage.py makemigrations
```

**Comment by Audiopolis** [comment]
I also have this issue, but for me, the file is called 0011_auto_20220217_1557. For whatever reason, this only happens when running the project in a Docker container, not when running `poetry add` or `pip install` locally.

**Comment by jpic** [comment]
None of these files were ever in this package: it was probably added by you!

Would be interesting to see the contents though

**Comment by Audiopolis** [comment]
They were absolutely added by me. Looks like migrations need to be made. The contents of the migration alter the `id` field of `city`, `country`, `region` and `subregion` to a `BigAutoField`.

If I uninstall the package and delete the migration (which still remains) from site-packages, then reinstall, the migration does not exist. When I run `makemigrations`, a migration file is created.

In order to ensure that my own migrations reference an existing migration name, I specify the name of the migration in this way:

`python manage.py makemigrations cities_light --name alter_id_fields`

Then, I recreate the migrations that depend on cities_light, so that the name becomes `0011_alter_id_fields` instead of `0011_auto_[timestamp]`.

Then I run `python manage.py makemigrations cities_light --name alter_id_fields` in my container's entrypoint _before_ running `migrate`.

Would a "migrations needed" pre-push check (that prevents push if `makemigrations` would have made migrations) have prevented this issue?

**Comment by jpic** [comment]
Not sure how we're supposed to deal with migrations in external apps: after
all each project may choose its own default id field type?

**Comment by Audiopolis** [comment]
Can't django-cities-light just provide its own `DEFAULT_AUTO_FIELD` setting?

**Comment by jpic** [comment]
Probably, should we keep serial or go with UUID ?

**Comment by marcelonp** [comment]
That migration is currently on the master branch and was added 14 days ago as of today, but it isn't present on release 3.9.0.

This causes issues on our build since we always get this:

`django.db.migrations.exceptions.NodeNotFoundError: Migration projects.0001_initial dependencies reference nonexistent parent node ('cities_light', '0011_alter_city_country_alter_city_id_alter_city_region_and_more')
`
for every new clone that we do. The workaround we found was commenting out the migration dependencies that reference this migration temporarily, then run makemigrations, and uncomment then back.

Wouldn't it be a good idea to add this migration as a hotfix release?

**Comment by marianoeramirez** [comment]
To everyone pending of this migration, now is on production. It was released under the 3.9.1 release.

**Comment by Audiopolis** [comment]
This is not the migration we needed. This alters foreign keys, not the ID fields mentioned. `makemigrations` _still_ results in `id` being changed to a `BigAutoField` for city, country, region and subregion.

**Comment by marianoeramirez** [comment]
Hi @Audiopolis  can you check with the last version deployed on pypi?
